#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Debian packaging.
#
export DEBMAIL="nickng@nickng.io"
export DEBFULLNAME="Nicholas Ng"

#
# Travis
#
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

#
# Homeshick
#
[ -f $HOME/.homesick/repos/homeshick/homeshick.sh ]
